import { Toaster } from "@/components/ui/sonner";

import Header from "@/components/Header";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";

import "./globals.css";
import Footer from "@/components/Footer";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>Future Rafay | shad cn Demo</title>
        <link rel="shortcut icon" href="https://vercel.com/favicon.ico" type="image/x-icon" />
      </head>
      <body>
        {/* Sidebar Provider wraps the sidebar components */}
        <SidebarProvider>
          <AppSidebar />
          <main>
            {/* Header component */}
            <Header />
            {/* Sidebar Trigger button */}
            
            {/* Main content */}
            {children}

            {/* Toaster for notifications */}
            <Toaster />
            <Footer />
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
