import { Toaster } from "@/components/ui/sonner";

import Header from "@/components/Header";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";

import "./globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {/* Sidebar Provider wraps the sidebar components */}
        <SidebarProvider>
          <AppSidebar />
          <main>
            {/* Header component */}
            <Header />
            {/* Sidebar Trigger button */}
            <SidebarTrigger />
            {/* Main content */}
            {children}
            {/* Toaster for notifications */}
            <Toaster />
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
